# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import (
    DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__,
)


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(
        self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[
            typing.Union[
                baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]
            ]
        ] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[
            typing.Callable[[str, baml_py.baml_py.FunctionLog], None]
        ] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
        return self.__stream_client

    @property
    def request(self):
        return self.__http_request

    @property
    def stream_request(self):
        return self.__http_stream_request

    @property
    def parse(self):
        return self.__llm_response_parser

    @property
    def parse_stream(self):
        return self.__llm_stream_parser

    async def EvaluateCompliance(
        self,
        facts_list: typing.List[str],
        control: types.Control,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.RuleEvaluation"]:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.EvaluateCompliance(
                facts_list=facts_list, control=control, baml_options=baml_options
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="EvaluateCompliance",
                args={
                    "facts_list": facts_list,
                    "control": control,
                },
            )
            return typing.cast(
                typing.List["types.RuleEvaluation"],
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def ExtractCIFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> types.CIFacts:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ExtractCIFacts(input=input, baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="ExtractCIFacts",
                args={
                    "input": input,
                },
            )
            return typing.cast(
                types.CIFacts,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def ExtractCommitFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> types.CommitFacts:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ExtractCommitFacts(
                input=input, baml_options=baml_options
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="ExtractCommitFacts",
                args={
                    "input": input,
                },
            )
            return typing.cast(
                types.CommitFacts,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def ExtractControl(
        self,
        control: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Control:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ExtractControl(
                control=control, baml_options=baml_options
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="ExtractControl",
                args={
                    "control": control,
                },
            )
            return typing.cast(
                types.Control,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def ExtractCoverageFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> types.CoverageFacts:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ExtractCoverageFacts(
                input=input, baml_options=baml_options
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="ExtractCoverageFacts",
                args={
                    "input": input,
                },
            )
            return typing.cast(
                types.CoverageFacts,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def ExtractIssueBoardFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> types.IssueBoardFacts:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ExtractIssueBoardFacts(
                input=input, baml_options=baml_options
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="ExtractIssueBoardFacts",
                args={
                    "input": input,
                },
            )
            return typing.cast(
                types.IssueBoardFacts,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def ExtractPRFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> types.PRFacts:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ExtractPRFacts(input=input, baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="ExtractPRFacts",
                args={
                    "input": input,
                },
            )
            return typing.cast(
                types.PRFacts,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def ExtractPerformanceFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> types.PerformanceFacts:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ExtractPerformanceFacts(
                input=input, baml_options=baml_options
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="ExtractPerformanceFacts",
                args={
                    "input": input,
                },
            )
            return typing.cast(
                types.PerformanceFacts,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def ExtractSecurityFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> types.SecurityFacts:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ExtractSecurityFacts(
                input=input, baml_options=baml_options
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="ExtractSecurityFacts",
                args={
                    "input": input,
                },
            )
            return typing.cast(
                types.SecurityFacts,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def ExtractTestResultFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> types.TestResultFacts:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ExtractTestResultFacts(
                input=input, baml_options=baml_options
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="ExtractTestResultFacts",
                args={
                    "input": input,
                },
            )
            return typing.cast(
                types.TestResultFacts,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def IdentifyEvidenceType(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> types.EvidenceType:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.IdentifyEvidenceType(
                input=input, baml_options=baml_options
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="IdentifyEvidenceType",
                args={
                    "input": input,
                },
            )
            return typing.cast(
                types.EvidenceType,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def EvaluateCompliance(
        self,
        facts_list: typing.List[str],
        control: types.Control,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[
        typing.List["stream_types.RuleEvaluation"], typing.List["types.RuleEvaluation"]
    ]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="EvaluateCompliance",
            args={
                "facts_list": facts_list,
                "control": control,
            },
        )
        return baml_py.BamlStream[
            typing.List["stream_types.RuleEvaluation"],
            typing.List["types.RuleEvaluation"],
        ](
            result,
            lambda x: typing.cast(
                typing.List["stream_types.RuleEvaluation"],
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                typing.List["types.RuleEvaluation"],
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def ExtractCIFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.CIFacts, types.CIFacts]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="ExtractCIFacts",
            args={
                "input": input,
            },
        )
        return baml_py.BamlStream[stream_types.CIFacts, types.CIFacts](
            result,
            lambda x: typing.cast(
                stream_types.CIFacts,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.CIFacts, x.cast_to(types, types, stream_types, False, __runtime__)
            ),
            ctx,
        )

    def ExtractCommitFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.CommitFacts, types.CommitFacts]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="ExtractCommitFacts",
            args={
                "input": input,
            },
        )
        return baml_py.BamlStream[stream_types.CommitFacts, types.CommitFacts](
            result,
            lambda x: typing.cast(
                stream_types.CommitFacts,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.CommitFacts,
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def ExtractControl(
        self,
        control: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.Control, types.Control]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="ExtractControl",
            args={
                "control": control,
            },
        )
        return baml_py.BamlStream[stream_types.Control, types.Control](
            result,
            lambda x: typing.cast(
                stream_types.Control,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.Control, x.cast_to(types, types, stream_types, False, __runtime__)
            ),
            ctx,
        )

    def ExtractCoverageFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.CoverageFacts, types.CoverageFacts]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="ExtractCoverageFacts",
            args={
                "input": input,
            },
        )
        return baml_py.BamlStream[stream_types.CoverageFacts, types.CoverageFacts](
            result,
            lambda x: typing.cast(
                stream_types.CoverageFacts,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.CoverageFacts,
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def ExtractIssueBoardFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.IssueBoardFacts, types.IssueBoardFacts]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="ExtractIssueBoardFacts",
            args={
                "input": input,
            },
        )
        return baml_py.BamlStream[stream_types.IssueBoardFacts, types.IssueBoardFacts](
            result,
            lambda x: typing.cast(
                stream_types.IssueBoardFacts,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.IssueBoardFacts,
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def ExtractPRFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.PRFacts, types.PRFacts]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="ExtractPRFacts",
            args={
                "input": input,
            },
        )
        return baml_py.BamlStream[stream_types.PRFacts, types.PRFacts](
            result,
            lambda x: typing.cast(
                stream_types.PRFacts,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.PRFacts, x.cast_to(types, types, stream_types, False, __runtime__)
            ),
            ctx,
        )

    def ExtractPerformanceFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.PerformanceFacts, types.PerformanceFacts]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="ExtractPerformanceFacts",
            args={
                "input": input,
            },
        )
        return baml_py.BamlStream[
            stream_types.PerformanceFacts, types.PerformanceFacts
        ](
            result,
            lambda x: typing.cast(
                stream_types.PerformanceFacts,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.PerformanceFacts,
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def ExtractSecurityFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.SecurityFacts, types.SecurityFacts]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="ExtractSecurityFacts",
            args={
                "input": input,
            },
        )
        return baml_py.BamlStream[stream_types.SecurityFacts, types.SecurityFacts](
            result,
            lambda x: typing.cast(
                stream_types.SecurityFacts,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.SecurityFacts,
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def ExtractTestResultFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.TestResultFacts, types.TestResultFacts]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="ExtractTestResultFacts",
            args={
                "input": input,
            },
        )
        return baml_py.BamlStream[stream_types.TestResultFacts, types.TestResultFacts](
            result,
            lambda x: typing.cast(
                stream_types.TestResultFacts,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.TestResultFacts,
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def IdentifyEvidenceType(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[types.EvidenceType, types.EvidenceType]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="IdentifyEvidenceType",
            args={
                "input": input,
            },
        )
        return baml_py.BamlStream[types.EvidenceType, types.EvidenceType](
            result,
            lambda x: typing.cast(
                types.EvidenceType,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.EvidenceType,
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )


class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def EvaluateCompliance(
        self,
        facts_list: typing.List[str],
        control: types.Control,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="EvaluateCompliance",
            args={
                "facts_list": facts_list,
                "control": control,
            },
            mode="request",
        )
        return result

    async def ExtractCIFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractCIFacts",
            args={
                "input": input,
            },
            mode="request",
        )
        return result

    async def ExtractCommitFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractCommitFacts",
            args={
                "input": input,
            },
            mode="request",
        )
        return result

    async def ExtractControl(
        self,
        control: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractControl",
            args={
                "control": control,
            },
            mode="request",
        )
        return result

    async def ExtractCoverageFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractCoverageFacts",
            args={
                "input": input,
            },
            mode="request",
        )
        return result

    async def ExtractIssueBoardFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractIssueBoardFacts",
            args={
                "input": input,
            },
            mode="request",
        )
        return result

    async def ExtractPRFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractPRFacts",
            args={
                "input": input,
            },
            mode="request",
        )
        return result

    async def ExtractPerformanceFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractPerformanceFacts",
            args={
                "input": input,
            },
            mode="request",
        )
        return result

    async def ExtractSecurityFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractSecurityFacts",
            args={
                "input": input,
            },
            mode="request",
        )
        return result

    async def ExtractTestResultFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractTestResultFacts",
            args={
                "input": input,
            },
            mode="request",
        )
        return result

    async def IdentifyEvidenceType(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="IdentifyEvidenceType",
            args={
                "input": input,
            },
            mode="request",
        )
        return result


class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def EvaluateCompliance(
        self,
        facts_list: typing.List[str],
        control: types.Control,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="EvaluateCompliance",
            args={
                "facts_list": facts_list,
                "control": control,
            },
            mode="stream",
        )
        return result

    async def ExtractCIFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractCIFacts",
            args={
                "input": input,
            },
            mode="stream",
        )
        return result

    async def ExtractCommitFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractCommitFacts",
            args={
                "input": input,
            },
            mode="stream",
        )
        return result

    async def ExtractControl(
        self,
        control: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractControl",
            args={
                "control": control,
            },
            mode="stream",
        )
        return result

    async def ExtractCoverageFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractCoverageFacts",
            args={
                "input": input,
            },
            mode="stream",
        )
        return result

    async def ExtractIssueBoardFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractIssueBoardFacts",
            args={
                "input": input,
            },
            mode="stream",
        )
        return result

    async def ExtractPRFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractPRFacts",
            args={
                "input": input,
            },
            mode="stream",
        )
        return result

    async def ExtractPerformanceFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractPerformanceFacts",
            args={
                "input": input,
            },
            mode="stream",
        )
        return result

    async def ExtractSecurityFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractSecurityFacts",
            args={
                "input": input,
            },
            mode="stream",
        )
        return result

    async def ExtractTestResultFacts(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractTestResultFacts",
            args={
                "input": input,
            },
            mode="stream",
        )
        return result

    async def IdentifyEvidenceType(
        self,
        input: types.EvidenceInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="IdentifyEvidenceType",
            args={
                "input": input,
            },
            mode="stream",
        )
        return result


b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))
