# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions


class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def EvaluateCompliance(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.RuleEvaluation"]:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="EvaluateCompliance",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(typing.List["types.RuleEvaluation"], result)

    def ExtractCIFacts(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.CIFacts:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractCIFacts", llm_response=llm_response, mode="request"
        )
        return typing.cast(types.CIFacts, result)

    def ExtractCommitFacts(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.CommitFacts:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractCommitFacts",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.CommitFacts, result)

    def ExtractControl(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Control:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractControl", llm_response=llm_response, mode="request"
        )
        return typing.cast(types.Control, result)

    def ExtractCoverageFacts(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.CoverageFacts:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractCoverageFacts",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.CoverageFacts, result)

    def ExtractIssueBoardFacts(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.IssueBoardFacts:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractIssueBoardFacts",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.IssueBoardFacts, result)

    def ExtractPRFacts(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PRFacts:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractPRFacts", llm_response=llm_response, mode="request"
        )
        return typing.cast(types.PRFacts, result)

    def ExtractPerformanceFacts(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PerformanceFacts:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractPerformanceFacts",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.PerformanceFacts, result)

    def ExtractSecurityFacts(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SecurityFacts:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractSecurityFacts",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.SecurityFacts, result)

    def ExtractTestResultFacts(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.TestResultFacts:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractTestResultFacts",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.TestResultFacts, result)

    def IdentifyEvidenceType(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.EvidenceType:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="IdentifyEvidenceType",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.EvidenceType, result)


class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def EvaluateCompliance(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.RuleEvaluation"]:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="EvaluateCompliance", llm_response=llm_response, mode="stream"
        )
        return typing.cast(typing.List["stream_types.RuleEvaluation"], result)

    def ExtractCIFacts(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.CIFacts:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractCIFacts", llm_response=llm_response, mode="stream"
        )
        return typing.cast(stream_types.CIFacts, result)

    def ExtractCommitFacts(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.CommitFacts:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractCommitFacts", llm_response=llm_response, mode="stream"
        )
        return typing.cast(stream_types.CommitFacts, result)

    def ExtractControl(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.Control:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractControl", llm_response=llm_response, mode="stream"
        )
        return typing.cast(stream_types.Control, result)

    def ExtractCoverageFacts(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.CoverageFacts:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractCoverageFacts",
            llm_response=llm_response,
            mode="stream",
        )
        return typing.cast(stream_types.CoverageFacts, result)

    def ExtractIssueBoardFacts(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.IssueBoardFacts:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractIssueBoardFacts",
            llm_response=llm_response,
            mode="stream",
        )
        return typing.cast(stream_types.IssueBoardFacts, result)

    def ExtractPRFacts(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.PRFacts:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractPRFacts", llm_response=llm_response, mode="stream"
        )
        return typing.cast(stream_types.PRFacts, result)

    def ExtractPerformanceFacts(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.PerformanceFacts:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractPerformanceFacts",
            llm_response=llm_response,
            mode="stream",
        )
        return typing.cast(stream_types.PerformanceFacts, result)

    def ExtractSecurityFacts(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.SecurityFacts:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractSecurityFacts",
            llm_response=llm_response,
            mode="stream",
        )
        return typing.cast(stream_types.SecurityFacts, result)

    def ExtractTestResultFacts(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.TestResultFacts:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractTestResultFacts",
            llm_response=llm_response,
            mode="stream",
        )
        return typing.cast(stream_types.TestResultFacts, result)

    def IdentifyEvidenceType(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.EvidenceType:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="IdentifyEvidenceType",
            llm_response=llm_response,
            mode="stream",
        )
        return typing.cast(types.EvidenceType, result)
