# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar("StreamStateValueT")


class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]


# #########################################################################
# Generated classes (12)
# #########################################################################


class CIFacts(BaseModel):
    pipeline_id: typing.Optional[str] = None
    overall_status: typing.Optional[str] = None
    stage_statuses: typing.Dict[str, str]
    environment: typing.Optional[str] = None
    has_warnings: typing.Optional[bool] = None


class CommitFacts(BaseModel):
    commit_hash: typing.Optional[str] = None
    author_username: typing.Optional[str] = None
    commit_message: typing.Optional[str] = None
    is_verified_signature: typing.Optional[bool] = None
    parent_pr_id: typing.Optional[str] = None


class Control(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    rules: typing.List["Rule"]


class CoverageFacts(BaseModel):
    tool_name: typing.Optional[str] = None
    overall_line_coverage: typing.Optional[float] = None
    new_code_line_coverage: typing.Optional[float] = None
    branch_coverage: typing.Optional[float] = None
    function_coverage: typing.Optional[float] = None
    visible_files_tested: typing.List[str]


class EvidenceInput(BaseModel):
    img: typing.Optional[baml_py.Image] = None
    text: typing.Optional[str] = None
    pdf_file: typing.Optional[baml_py.Image] = None
    audio_file: typing.Optional[baml_py.Image] = None
    video_file: typing.Optional[baml_py.Image] = None


class IssueBoardFacts(BaseModel):
    board_name: typing.Optional[str] = None
    sprint_name: typing.Optional[str] = None
    visible_columns: typing.List[str]
    active_ticket_count: typing.Optional[int] = None
    assignees_visible: typing.List[str]


class PRFacts(BaseModel):
    platform: typing.Optional[str] = None
    pr_number: typing.Optional[str] = None
    author_username: typing.Optional[str] = None
    reviewer_usernames: typing.List[str]
    status: typing.Optional[str] = None
    base_branch: typing.Optional[str] = None
    status_checks_passing: typing.Optional[bool] = None


class PerformanceFacts(BaseModel):
    tool_name: typing.Optional[str] = None
    performance_score: typing.Optional[int] = None
    avg_response_time_ms: typing.Optional[float] = None
    p95_response_time_ms: typing.Optional[float] = None
    throughput_rps: typing.Optional[float] = None
    error_rate_percent: typing.Optional[float] = None


class Rule(BaseModel):
    id: typing.Optional[str] = None
    type: typing.Optional[types.RuleType] = None
    description: typing.Optional[str] = None
    logic: typing.Optional[str] = None
    exceptions: typing.List[str]


class RuleEvaluation(BaseModel):
    rule_id: typing.Optional[str] = None
    status: typing.Optional[types.RuleStatus] = None
    reasoning: typing.Optional[str] = None


class SecurityFacts(BaseModel):
    scanner_name: typing.Optional[str] = None
    severity_counts: typing.Dict[str, int]
    total_vulnerabilities: typing.Optional[int] = None
    top_critical_issues: typing.List[str]
    is_passing: typing.Optional[bool] = None


class TestResultFacts(BaseModel):
    framework: typing.Optional[str] = None
    total_tests: typing.Optional[int] = None
    passed: typing.Optional[int] = None
    failed: typing.Optional[int] = None
    skipped: typing.Optional[int] = None
    duration_seconds: typing.Optional[float] = None
    failed_test_names: typing.List[str]


# #########################################################################
# Generated type aliases (0)
# #########################################################################
