# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar("StreamStateValueT")


class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]


# #########################################################################
# Generated classes (3)
# #########################################################################


class Control(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    rules: typing.List["Rule"]


class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]


class Rule(BaseModel):
    id: typing.Optional[str] = None
    type: typing.Optional[types.RuleType] = None
    description: typing.Optional[str] = None
    logic: typing.Optional[str] = None
    exceptions: typing.List[str]


# #########################################################################
# Generated type aliases (0)
# #########################################################################
