# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import (
    DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__,
)


class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(
        self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[
            typing.Union[
                baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]
            ]
        ] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[
            typing.Callable[[str, baml_py.baml_py.FunctionLog], None]
        ] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
        return self.__stream_client

    @property
    def request(self):
        return self.__http_request

    @property
    def stream_request(self):
        return self.__http_stream_request

    @property
    def parse(self):
        return self.__llm_response_parser

    @property
    def parse_stream(self):
        return self.__llm_stream_parser

    def EvaluateCompliance(
        self,
        facts: str,
        control: types.Control,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.RuleEvaluation"]:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            stream = self.stream.EvaluateCompliance(
                facts=facts, control=control, baml_options=baml_options
            )
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(
                function_name="EvaluateCompliance",
                args={
                    "facts": facts,
                    "control": control,
                },
            )
            return typing.cast(
                typing.List["types.RuleEvaluation"],
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    def ExtractCIFacts(
        self,
        img: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> types.CIFacts:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            stream = self.stream.ExtractCIFacts(img=img, baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(
                function_name="ExtractCIFacts",
                args={
                    "img": img,
                },
            )
            return typing.cast(
                types.CIFacts,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    def ExtractControl(
        self,
        control: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Control:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            stream = self.stream.ExtractControl(
                control=control, baml_options=baml_options
            )
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(
                function_name="ExtractControl",
                args={
                    "control": control,
                },
            )
            return typing.cast(
                types.Control,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    def ExtractCoverageFacts(
        self,
        img: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> types.CoverageFacts:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            stream = self.stream.ExtractCoverageFacts(
                img=img, baml_options=baml_options
            )
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(
                function_name="ExtractCoverageFacts",
                args={
                    "img": img,
                },
            )
            return typing.cast(
                types.CoverageFacts,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    def ExtractPRFacts(
        self,
        img: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> types.PRFacts:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            stream = self.stream.ExtractPRFacts(img=img, baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(
                function_name="ExtractPRFacts",
                args={
                    "img": img,
                },
            )
            return typing.cast(
                types.PRFacts,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    def IdentifyEvidenceType(
        self,
        img: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> types.EvidenceType:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            stream = self.stream.IdentifyEvidenceType(
                img=img, baml_options=baml_options
            )
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(
                function_name="IdentifyEvidenceType",
                args={
                    "img": img,
                },
            )
            return typing.cast(
                types.EvidenceType,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def EvaluateCompliance(
        self,
        facts: str,
        control: types.Control,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[
        typing.List["stream_types.RuleEvaluation"], typing.List["types.RuleEvaluation"]
    ]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(
            function_name="EvaluateCompliance",
            args={
                "facts": facts,
                "control": control,
            },
        )
        return baml_py.BamlSyncStream[
            typing.List["stream_types.RuleEvaluation"],
            typing.List["types.RuleEvaluation"],
        ](
            result,
            lambda x: typing.cast(
                typing.List["stream_types.RuleEvaluation"],
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                typing.List["types.RuleEvaluation"],
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def ExtractCIFacts(
        self,
        img: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.CIFacts, types.CIFacts]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(
            function_name="ExtractCIFacts",
            args={
                "img": img,
            },
        )
        return baml_py.BamlSyncStream[stream_types.CIFacts, types.CIFacts](
            result,
            lambda x: typing.cast(
                stream_types.CIFacts,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.CIFacts, x.cast_to(types, types, stream_types, False, __runtime__)
            ),
            ctx,
        )

    def ExtractControl(
        self,
        control: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Control, types.Control]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(
            function_name="ExtractControl",
            args={
                "control": control,
            },
        )
        return baml_py.BamlSyncStream[stream_types.Control, types.Control](
            result,
            lambda x: typing.cast(
                stream_types.Control,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.Control, x.cast_to(types, types, stream_types, False, __runtime__)
            ),
            ctx,
        )

    def ExtractCoverageFacts(
        self,
        img: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.CoverageFacts, types.CoverageFacts]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(
            function_name="ExtractCoverageFacts",
            args={
                "img": img,
            },
        )
        return baml_py.BamlSyncStream[stream_types.CoverageFacts, types.CoverageFacts](
            result,
            lambda x: typing.cast(
                stream_types.CoverageFacts,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.CoverageFacts,
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def ExtractPRFacts(
        self,
        img: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.PRFacts, types.PRFacts]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(
            function_name="ExtractPRFacts",
            args={
                "img": img,
            },
        )
        return baml_py.BamlSyncStream[stream_types.PRFacts, types.PRFacts](
            result,
            lambda x: typing.cast(
                stream_types.PRFacts,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.PRFacts, x.cast_to(types, types, stream_types, False, __runtime__)
            ),
            ctx,
        )

    def IdentifyEvidenceType(
        self,
        img: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[types.EvidenceType, types.EvidenceType]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(
            function_name="IdentifyEvidenceType",
            args={
                "img": img,
            },
        )
        return baml_py.BamlSyncStream[types.EvidenceType, types.EvidenceType](
            result,
            lambda x: typing.cast(
                types.EvidenceType,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.EvidenceType,
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )


class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def EvaluateCompliance(
        self,
        facts: str,
        control: types.Control,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="EvaluateCompliance",
            args={
                "facts": facts,
                "control": control,
            },
            mode="request",
        )
        return result

    def ExtractCIFacts(
        self,
        img: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="ExtractCIFacts",
            args={
                "img": img,
            },
            mode="request",
        )
        return result

    def ExtractControl(
        self,
        control: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="ExtractControl",
            args={
                "control": control,
            },
            mode="request",
        )
        return result

    def ExtractCoverageFacts(
        self,
        img: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="ExtractCoverageFacts",
            args={
                "img": img,
            },
            mode="request",
        )
        return result

    def ExtractPRFacts(
        self,
        img: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="ExtractPRFacts",
            args={
                "img": img,
            },
            mode="request",
        )
        return result

    def IdentifyEvidenceType(
        self,
        img: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="IdentifyEvidenceType",
            args={
                "img": img,
            },
            mode="request",
        )
        return result


class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def EvaluateCompliance(
        self,
        facts: str,
        control: types.Control,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="EvaluateCompliance",
            args={
                "facts": facts,
                "control": control,
            },
            mode="stream",
        )
        return result

    def ExtractCIFacts(
        self,
        img: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="ExtractCIFacts",
            args={
                "img": img,
            },
            mode="stream",
        )
        return result

    def ExtractControl(
        self,
        control: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="ExtractControl",
            args={
                "control": control,
            },
            mode="stream",
        )
        return result

    def ExtractCoverageFacts(
        self,
        img: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="ExtractCoverageFacts",
            args={
                "img": img,
            },
            mode="stream",
        )
        return result

    def ExtractPRFacts(
        self,
        img: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="ExtractPRFacts",
            args={
                "img": img,
            },
            mode="stream",
        )
        return result

    def IdentifyEvidenceType(
        self,
        img: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="IdentifyEvidenceType",
            args={
                "img": img,
            },
            mode="stream",
        )
        return result


b = BamlSyncClient(DoNotUseDirectlyCallManager({}))
