# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {
    "types.CIFacts": types.CIFacts,
    "stream_types.CIFacts": stream_types.CIFacts,
    "types.Control": types.Control,
    "stream_types.Control": stream_types.Control,
    "types.CoverageFacts": types.CoverageFacts,
    "stream_types.CoverageFacts": stream_types.CoverageFacts,
    "types.PRFacts": types.PRFacts,
    "stream_types.PRFacts": stream_types.PRFacts,
    "types.Rule": types.Rule,
    "stream_types.Rule": stream_types.Rule,
    "types.RuleEvaluation": types.RuleEvaluation,
    "stream_types.RuleEvaluation": stream_types.RuleEvaluation,
    "types.EvidenceType": types.EvidenceType,
    "types.RuleType": types.RuleType,
}
