# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
from baml_py import type_builder
from baml_py import baml_py

# These are exports, not used here, hence the linter is disabled
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder  # noqa: F401 # pylint: disable=unused-import
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME


class TypeBuilder(type_builder.TypeBuilder):
    def __init__(self):
        super().__init__(
            classes=set(
                [
                    "CIFacts",
                    "Control",
                    "CoverageFacts",
                    "PRFacts",
                    "Rule",
                    "RuleEvaluation",
                ]
            ),
            enums=set(
                [
                    "EvidenceType",
                    "RuleStatus",
                    "RuleType",
                ]
            ),
            runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
        )

    # #########################################################################
    # Generated enums 3
    # #########################################################################

    @property
    def EvidenceType(self) -> "EvidenceTypeViewer":
        return EvidenceTypeViewer(self)

    @property
    def RuleStatus(self) -> "RuleStatusViewer":
        return RuleStatusViewer(self)

    @property
    def RuleType(self) -> "RuleTypeViewer":
        return RuleTypeViewer(self)

    # #########################################################################
    # Generated classes 6
    # #########################################################################

    @property
    def CIFacts(self) -> "CIFactsViewer":
        return CIFactsViewer(self)

    @property
    def Control(self) -> "ControlViewer":
        return ControlViewer(self)

    @property
    def CoverageFacts(self) -> "CoverageFactsViewer":
        return CoverageFactsViewer(self)

    @property
    def PRFacts(self) -> "PRFactsViewer":
        return PRFactsViewer(self)

    @property
    def Rule(self) -> "RuleViewer":
        return RuleViewer(self)

    @property
    def RuleEvaluation(self) -> "RuleEvaluationViewer":
        return RuleEvaluationViewer(self)


# #########################################################################
# Generated enums 3
# #########################################################################


class EvidenceTypeAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("EvidenceType")
        self._values: typing.Set[str] = set(
            [
                "PullRequest",
                "CoverageReport",
                "CIPipeline",
                "Unknown",
            ]
        )
        self._vals = EvidenceTypeValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "EvidenceTypeValues":
        return self._vals


class EvidenceTypeViewer(EvidenceTypeAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_values(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [
            (name, type_builder.EnumValueViewer(self._bldr.value(name)))
            for name in self._values
        ]


class EvidenceTypeValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def PullRequest(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("PullRequest"))

    @property
    def CoverageReport(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("CoverageReport"))

    @property
    def CIPipeline(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("CIPipeline"))

    @property
    def Unknown(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Unknown"))


class RuleStatusAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("RuleStatus")
        self._values: typing.Set[str] = set(
            [
                "PASS",
                "FAIL",
                "MORE_INFOMATION_NEEDED",
                "NA",
            ]
        )
        self._vals = RuleStatusValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "RuleStatusValues":
        return self._vals


class RuleStatusViewer(RuleStatusAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_values(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [
            (name, type_builder.EnumValueViewer(self._bldr.value(name)))
            for name in self._values
        ]


class RuleStatusValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def PASS(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("PASS"))

    @property
    def FAIL(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("FAIL"))

    @property
    def MORE_INFOMATION_NEEDED(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MORE_INFOMATION_NEEDED"))

    @property
    def NA(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("NA"))


class RuleTypeAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("RuleType")
        self._values: typing.Set[str] = set(
            [
                "Blocking",
                "Audit",
            ]
        )
        self._vals = RuleTypeValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "RuleTypeValues":
        return self._vals


class RuleTypeViewer(RuleTypeAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_values(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [
            (name, type_builder.EnumValueViewer(self._bldr.value(name)))
            for name in self._values
        ]


class RuleTypeValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def Blocking(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Blocking"))

    @property
    def Audit(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Audit"))


# #########################################################################
# Generated classes 6
# #########################################################################


class CIFactsAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("CIFacts")
        self._properties: typing.Set[str] = set(
            [
                "pipeline_id",
                "overall_status",
                "stage_statuses",
                "environment",
                "has_warnings",
            ]
        )
        self._props = CIFactsProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "CIFactsProperties":
        return self._props


class CIFactsViewer(CIFactsAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class CIFactsProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def pipeline_id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("pipeline_id"))

    @property
    def overall_status(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("overall_status"))

    @property
    def stage_statuses(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("stage_statuses"))

    @property
    def environment(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("environment"))

    @property
    def has_warnings(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("has_warnings"))


class ControlAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Control")
        self._properties: typing.Set[str] = set(
            [
                "name",
                "description",
                "rules",
            ]
        )
        self._props = ControlProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ControlProperties":
        return self._props


class ControlViewer(ControlAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class ControlProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("name"))

    @property
    def description(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("description"))

    @property
    def rules(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("rules"))


class CoverageFactsAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("CoverageFacts")
        self._properties: typing.Set[str] = set(
            [
                "tool_name",
                "overall_line_coverage",
                "new_code_line_coverage",
                "branch_coverage",
                "function_coverage",
                "visible_files_tested",
            ]
        )
        self._props = CoverageFactsProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "CoverageFactsProperties":
        return self._props


class CoverageFactsViewer(CoverageFactsAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class CoverageFactsProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def tool_name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("tool_name"))

    @property
    def overall_line_coverage(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("overall_line_coverage")
        )

    @property
    def new_code_line_coverage(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("new_code_line_coverage")
        )

    @property
    def branch_coverage(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("branch_coverage"))

    @property
    def function_coverage(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("function_coverage")
        )

    @property
    def visible_files_tested(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("visible_files_tested")
        )


class PRFactsAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("PRFacts")
        self._properties: typing.Set[str] = set(
            [
                "platform",
                "pr_number",
                "author_username",
                "reviewer_usernames",
                "status",
                "base_branch",
                "status_checks_passing",
            ]
        )
        self._props = PRFactsProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "PRFactsProperties":
        return self._props


class PRFactsViewer(PRFactsAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class PRFactsProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def platform(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("platform"))

    @property
    def pr_number(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("pr_number"))

    @property
    def author_username(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("author_username"))

    @property
    def reviewer_usernames(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("reviewer_usernames")
        )

    @property
    def status(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("status"))

    @property
    def base_branch(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("base_branch"))

    @property
    def status_checks_passing(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("status_checks_passing")
        )


class RuleAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Rule")
        self._properties: typing.Set[str] = set(
            [
                "id",
                "type",
                "description",
                "logic",
                "exceptions",
            ]
        )
        self._props = RuleProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "RuleProperties":
        return self._props


class RuleViewer(RuleAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class RuleProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("id"))

    @property
    def type(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("type"))

    @property
    def description(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("description"))

    @property
    def logic(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("logic"))

    @property
    def exceptions(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("exceptions"))


class RuleEvaluationAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("RuleEvaluation")
        self._properties: typing.Set[str] = set(
            [
                "rule_id",
                "status",
                "reasoning",
            ]
        )
        self._props = RuleEvaluationProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "RuleEvaluationProperties":
        return self._props


class RuleEvaluationViewer(RuleEvaluationAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class RuleEvaluationProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def rule_id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("rule_id"))

    @property
    def status(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("status"))

    @property
    def reasoning(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("reasoning"))
