# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
from baml_py import type_builder
from baml_py import baml_py

# These are exports, not used here, hence the linter is disabled
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder  # noqa: F401 # pylint: disable=unused-import
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME


class TypeBuilder(type_builder.TypeBuilder):
    def __init__(self):
        super().__init__(
            classes=set(
                [
                    "Control",
                    "ControlEvaluationResult",
                    "Rule",
                    "RuleEvaluation",
                ]
            ),
            enums=set(
                [
                    "RuleType",
                ]
            ),
            runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
        )

    # #########################################################################
    # Generated enums 1
    # #########################################################################

    @property
    def RuleType(self) -> "RuleTypeViewer":
        return RuleTypeViewer(self)

    # #########################################################################
    # Generated classes 4
    # #########################################################################

    @property
    def Control(self) -> "ControlViewer":
        return ControlViewer(self)

    @property
    def ControlEvaluationResult(self) -> "ControlEvaluationResultViewer":
        return ControlEvaluationResultViewer(self)

    @property
    def Rule(self) -> "RuleViewer":
        return RuleViewer(self)

    @property
    def RuleEvaluation(self) -> "RuleEvaluationViewer":
        return RuleEvaluationViewer(self)


# #########################################################################
# Generated enums 1
# #########################################################################


class RuleTypeAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("RuleType")
        self._values: typing.Set[str] = set(
            [
                "Blocking",
                "Audit",
            ]
        )
        self._vals = RuleTypeValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "RuleTypeValues":
        return self._vals


class RuleTypeViewer(RuleTypeAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_values(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [
            (name, type_builder.EnumValueViewer(self._bldr.value(name)))
            for name in self._values
        ]


class RuleTypeValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def Blocking(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Blocking"))

    @property
    def Audit(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Audit"))


# #########################################################################
# Generated classes 4
# #########################################################################


class ControlAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Control")
        self._properties: typing.Set[str] = set(
            [
                "name",
                "description",
                "rules",
            ]
        )
        self._props = ControlProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ControlProperties":
        return self._props


class ControlViewer(ControlAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class ControlProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("name"))

    @property
    def description(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("description"))

    @property
    def rules(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("rules"))


class ControlEvaluationResultAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ControlEvaluationResult")
        self._properties: typing.Set[str] = set(
            [
                "overall_status",
                "failing_rules",
                "missing_evidence_rules",
            ]
        )
        self._props = ControlEvaluationResultProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ControlEvaluationResultProperties":
        return self._props


class ControlEvaluationResultViewer(ControlEvaluationResultAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class ControlEvaluationResultProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def overall_status(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("overall_status"))

    @property
    def failing_rules(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("failing_rules"))

    @property
    def missing_evidence_rules(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("missing_evidence_rules")
        )


class RuleAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Rule")
        self._properties: typing.Set[str] = set(
            [
                "id",
                "type",
                "description",
                "logic",
                "exceptions",
            ]
        )
        self._props = RuleProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "RuleProperties":
        return self._props


class RuleViewer(RuleAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class RuleProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("id"))

    @property
    def type(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("type"))

    @property
    def description(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("description"))

    @property
    def logic(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("logic"))

    @property
    def exceptions(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("exceptions"))


class RuleEvaluationAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("RuleEvaluation")
        self._properties: typing.Set[str] = set(
            [
                "rule_id",
                "status",
                "reasoning",
            ]
        )
        self._props = RuleEvaluationProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "RuleEvaluationProperties":
        return self._props


class RuleEvaluationViewer(RuleEvaluationAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class RuleEvaluationProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def rule_id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("rule_id"))

    @property
    def status(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("status"))

    @property
    def reasoning(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("reasoning"))
