# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
from baml_py import type_builder
from baml_py import baml_py

# These are exports, not used here, hence the linter is disabled
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder  # noqa: F401 # pylint: disable=unused-import
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME


class TypeBuilder(type_builder.TypeBuilder):
    def __init__(self):
        super().__init__(
            classes=set(
                [
                    "CIFacts",
                    "CommitFacts",
                    "Control",
                    "CoverageFacts",
                    "EvidenceInput",
                    "IssueBoardFacts",
                    "PRFacts",
                    "PerformanceFacts",
                    "Rule",
                    "RuleEvaluation",
                    "SecurityFacts",
                    "TestResultFacts",
                ]
            ),
            enums=set(
                [
                    "EvidenceType",
                    "RuleStatus",
                    "RuleType",
                ]
            ),
            runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
        )

    # #########################################################################
    # Generated enums 3
    # #########################################################################

    @property
    def EvidenceType(self) -> "EvidenceTypeViewer":
        return EvidenceTypeViewer(self)

    @property
    def RuleStatus(self) -> "RuleStatusViewer":
        return RuleStatusViewer(self)

    @property
    def RuleType(self) -> "RuleTypeViewer":
        return RuleTypeViewer(self)

    # #########################################################################
    # Generated classes 12
    # #########################################################################

    @property
    def CIFacts(self) -> "CIFactsViewer":
        return CIFactsViewer(self)

    @property
    def CommitFacts(self) -> "CommitFactsViewer":
        return CommitFactsViewer(self)

    @property
    def Control(self) -> "ControlViewer":
        return ControlViewer(self)

    @property
    def CoverageFacts(self) -> "CoverageFactsViewer":
        return CoverageFactsViewer(self)

    @property
    def EvidenceInput(self) -> "EvidenceInputViewer":
        return EvidenceInputViewer(self)

    @property
    def IssueBoardFacts(self) -> "IssueBoardFactsViewer":
        return IssueBoardFactsViewer(self)

    @property
    def PRFacts(self) -> "PRFactsViewer":
        return PRFactsViewer(self)

    @property
    def PerformanceFacts(self) -> "PerformanceFactsViewer":
        return PerformanceFactsViewer(self)

    @property
    def Rule(self) -> "RuleViewer":
        return RuleViewer(self)

    @property
    def RuleEvaluation(self) -> "RuleEvaluationViewer":
        return RuleEvaluationViewer(self)

    @property
    def SecurityFacts(self) -> "SecurityFactsViewer":
        return SecurityFactsViewer(self)

    @property
    def TestResultFacts(self) -> "TestResultFactsViewer":
        return TestResultFactsViewer(self)


# #########################################################################
# Generated enums 3
# #########################################################################


class EvidenceTypeAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("EvidenceType")
        self._values: typing.Set[str] = set(
            [
                "PullRequest",
                "CoverageReport",
                "CIPipeline",
                "TestResult",
                "SecurityScan",
                "IssueBoard",
                "PerformanceReport",
                "GitCommit",
                "Unknown",
            ]
        )
        self._vals = EvidenceTypeValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "EvidenceTypeValues":
        return self._vals


class EvidenceTypeViewer(EvidenceTypeAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_values(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [
            (name, type_builder.EnumValueViewer(self._bldr.value(name)))
            for name in self._values
        ]


class EvidenceTypeValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def PullRequest(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("PullRequest"))

    @property
    def CoverageReport(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("CoverageReport"))

    @property
    def CIPipeline(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("CIPipeline"))

    @property
    def TestResult(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("TestResult"))

    @property
    def SecurityScan(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SecurityScan"))

    @property
    def IssueBoard(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("IssueBoard"))

    @property
    def PerformanceReport(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("PerformanceReport"))

    @property
    def GitCommit(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("GitCommit"))

    @property
    def Unknown(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Unknown"))


class RuleStatusAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("RuleStatus")
        self._values: typing.Set[str] = set(
            [
                "PASS",
                "FAIL",
                "MORE_INFOMATION_NEEDED",
                "NA",
            ]
        )
        self._vals = RuleStatusValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "RuleStatusValues":
        return self._vals


class RuleStatusViewer(RuleStatusAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_values(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [
            (name, type_builder.EnumValueViewer(self._bldr.value(name)))
            for name in self._values
        ]


class RuleStatusValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def PASS(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("PASS"))

    @property
    def FAIL(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("FAIL"))

    @property
    def MORE_INFOMATION_NEEDED(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MORE_INFOMATION_NEEDED"))

    @property
    def NA(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("NA"))


class RuleTypeAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("RuleType")
        self._values: typing.Set[str] = set(
            [
                "Blocking",
                "Audit",
            ]
        )
        self._vals = RuleTypeValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "RuleTypeValues":
        return self._vals


class RuleTypeViewer(RuleTypeAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_values(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [
            (name, type_builder.EnumValueViewer(self._bldr.value(name)))
            for name in self._values
        ]


class RuleTypeValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def Blocking(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Blocking"))

    @property
    def Audit(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Audit"))


# #########################################################################
# Generated classes 12
# #########################################################################


class CIFactsAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("CIFacts")
        self._properties: typing.Set[str] = set(
            [
                "pipeline_id",
                "overall_status",
                "stage_statuses",
                "environment",
                "has_warnings",
            ]
        )
        self._props = CIFactsProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "CIFactsProperties":
        return self._props


class CIFactsViewer(CIFactsAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class CIFactsProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def pipeline_id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("pipeline_id"))

    @property
    def overall_status(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("overall_status"))

    @property
    def stage_statuses(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("stage_statuses"))

    @property
    def environment(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("environment"))

    @property
    def has_warnings(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("has_warnings"))


class CommitFactsAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("CommitFacts")
        self._properties: typing.Set[str] = set(
            [
                "commit_hash",
                "author_username",
                "commit_message",
                "is_verified_signature",
                "parent_pr_id",
            ]
        )
        self._props = CommitFactsProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "CommitFactsProperties":
        return self._props


class CommitFactsViewer(CommitFactsAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class CommitFactsProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def commit_hash(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("commit_hash"))

    @property
    def author_username(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("author_username"))

    @property
    def commit_message(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("commit_message"))

    @property
    def is_verified_signature(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("is_verified_signature")
        )

    @property
    def parent_pr_id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("parent_pr_id"))


class ControlAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Control")
        self._properties: typing.Set[str] = set(
            [
                "name",
                "description",
                "rules",
            ]
        )
        self._props = ControlProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ControlProperties":
        return self._props


class ControlViewer(ControlAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class ControlProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("name"))

    @property
    def description(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("description"))

    @property
    def rules(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("rules"))


class CoverageFactsAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("CoverageFacts")
        self._properties: typing.Set[str] = set(
            [
                "tool_name",
                "overall_line_coverage",
                "new_code_line_coverage",
                "branch_coverage",
                "function_coverage",
                "visible_files_tested",
            ]
        )
        self._props = CoverageFactsProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "CoverageFactsProperties":
        return self._props


class CoverageFactsViewer(CoverageFactsAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class CoverageFactsProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def tool_name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("tool_name"))

    @property
    def overall_line_coverage(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("overall_line_coverage")
        )

    @property
    def new_code_line_coverage(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("new_code_line_coverage")
        )

    @property
    def branch_coverage(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("branch_coverage"))

    @property
    def function_coverage(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("function_coverage")
        )

    @property
    def visible_files_tested(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("visible_files_tested")
        )


class EvidenceInputAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("EvidenceInput")
        self._properties: typing.Set[str] = set(
            [
                "img",
                "text",
                "pdf_file",
                "audio_file",
                "video_file",
            ]
        )
        self._props = EvidenceInputProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "EvidenceInputProperties":
        return self._props


class EvidenceInputViewer(EvidenceInputAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class EvidenceInputProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def img(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("img"))

    @property
    def text(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("text"))

    @property
    def pdf_file(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("pdf_file"))

    @property
    def audio_file(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("audio_file"))

    @property
    def video_file(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("video_file"))


class IssueBoardFactsAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("IssueBoardFacts")
        self._properties: typing.Set[str] = set(
            [
                "board_name",
                "sprint_name",
                "visible_columns",
                "active_ticket_count",
                "assignees_visible",
            ]
        )
        self._props = IssueBoardFactsProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "IssueBoardFactsProperties":
        return self._props


class IssueBoardFactsViewer(IssueBoardFactsAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class IssueBoardFactsProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def board_name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("board_name"))

    @property
    def sprint_name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("sprint_name"))

    @property
    def visible_columns(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("visible_columns"))

    @property
    def active_ticket_count(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("active_ticket_count")
        )

    @property
    def assignees_visible(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("assignees_visible")
        )


class PRFactsAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("PRFacts")
        self._properties: typing.Set[str] = set(
            [
                "platform",
                "pr_number",
                "author_username",
                "reviewer_usernames",
                "status",
                "base_branch",
                "status_checks_passing",
            ]
        )
        self._props = PRFactsProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "PRFactsProperties":
        return self._props


class PRFactsViewer(PRFactsAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class PRFactsProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def platform(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("platform"))

    @property
    def pr_number(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("pr_number"))

    @property
    def author_username(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("author_username"))

    @property
    def reviewer_usernames(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("reviewer_usernames")
        )

    @property
    def status(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("status"))

    @property
    def base_branch(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("base_branch"))

    @property
    def status_checks_passing(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("status_checks_passing")
        )


class PerformanceFactsAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("PerformanceFacts")
        self._properties: typing.Set[str] = set(
            [
                "tool_name",
                "performance_score",
                "avg_response_time_ms",
                "p95_response_time_ms",
                "throughput_rps",
                "error_rate_percent",
            ]
        )
        self._props = PerformanceFactsProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "PerformanceFactsProperties":
        return self._props


class PerformanceFactsViewer(PerformanceFactsAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class PerformanceFactsProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def tool_name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("tool_name"))

    @property
    def performance_score(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("performance_score")
        )

    @property
    def avg_response_time_ms(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("avg_response_time_ms")
        )

    @property
    def p95_response_time_ms(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("p95_response_time_ms")
        )

    @property
    def throughput_rps(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("throughput_rps"))

    @property
    def error_rate_percent(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("error_rate_percent")
        )


class RuleAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Rule")
        self._properties: typing.Set[str] = set(
            [
                "id",
                "type",
                "description",
                "logic",
                "exceptions",
            ]
        )
        self._props = RuleProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "RuleProperties":
        return self._props


class RuleViewer(RuleAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class RuleProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("id"))

    @property
    def type(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("type"))

    @property
    def description(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("description"))

    @property
    def logic(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("logic"))

    @property
    def exceptions(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("exceptions"))


class RuleEvaluationAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("RuleEvaluation")
        self._properties: typing.Set[str] = set(
            [
                "rule_id",
                "status",
                "reasoning",
            ]
        )
        self._props = RuleEvaluationProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "RuleEvaluationProperties":
        return self._props


class RuleEvaluationViewer(RuleEvaluationAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class RuleEvaluationProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def rule_id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("rule_id"))

    @property
    def status(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("status"))

    @property
    def reasoning(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("reasoning"))


class SecurityFactsAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("SecurityFacts")
        self._properties: typing.Set[str] = set(
            [
                "scanner_name",
                "severity_counts",
                "total_vulnerabilities",
                "top_critical_issues",
                "is_passing",
            ]
        )
        self._props = SecurityFactsProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "SecurityFactsProperties":
        return self._props


class SecurityFactsViewer(SecurityFactsAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class SecurityFactsProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def scanner_name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("scanner_name"))

    @property
    def severity_counts(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("severity_counts"))

    @property
    def total_vulnerabilities(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("total_vulnerabilities")
        )

    @property
    def top_critical_issues(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("top_critical_issues")
        )

    @property
    def is_passing(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("is_passing"))


class TestResultFactsAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb  # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("TestResultFacts")
        self._properties: typing.Set[str] = set(
            [
                "framework",
                "total_tests",
                "passed",
                "failed",
                "skipped",
                "duration_seconds",
                "failed_test_names",
            ]
        )
        self._props = TestResultFactsProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "TestResultFactsProperties":
        return self._props


class TestResultFactsViewer(TestResultFactsAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    def list_properties(
        self,
    ) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [
            (name, type_builder.ClassPropertyViewer(self._bldr.property(name)))
            for name in self._properties
        ]


class TestResultFactsProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties  # type: ignore (we know how to use this private attribute) # noqa: F821

    @property
    def framework(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("framework"))

    @property
    def total_tests(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("total_tests"))

    @property
    def passed(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("passed"))

    @property
    def failed(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("failed"))

    @property
    def skipped(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("skipped"))

    @property
    def duration_seconds(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("duration_seconds")
        )

    @property
    def failed_test_names(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(
            self.__bldr.property("failed_test_names")
        )
