# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar("CheckT")
CheckName = typing_extensions.TypeVar("CheckName", bound=str)


class Check(BaseModel):
    name: str
    expression: str
    status: str


class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]


def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())


def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))


# #########################################################################
# Generated enums (3)
# #########################################################################


class EvidenceType(str, Enum):
    PullRequest = "PullRequest"
    CoverageReport = "CoverageReport"
    CIPipeline = "CIPipeline"
    Unknown = "Unknown"


class RuleStatus(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    MORE_INFOMATION_NEEDED = "MORE_INFOMATION_NEEDED"
    NA = "NA"


class RuleType(str, Enum):
    Blocking = "Blocking"
    Audit = "Audit"


# #########################################################################
# Generated classes (6)
# #########################################################################


class CIFacts(BaseModel):
    pipeline_id: typing.Optional[str] = None
    overall_status: typing.Optional[str] = None
    stage_statuses: typing.Dict[str, str]
    environment: typing.Optional[str] = None
    has_warnings: bool


class Control(BaseModel):
    name: str
    description: str
    rules: typing.List["Rule"]


class CoverageFacts(BaseModel):
    tool_name: typing.Optional[str] = None
    overall_line_coverage: typing.Optional[float] = None
    new_code_line_coverage: typing.Optional[float] = None
    branch_coverage: typing.Optional[float] = None
    function_coverage: typing.Optional[float] = None
    visible_files_tested: typing.List[str]


class PRFacts(BaseModel):
    platform: typing.Optional[str] = None
    pr_number: typing.Optional[str] = None
    author_username: typing.Optional[str] = None
    reviewer_usernames: typing.List[str]
    status: typing.Optional[str] = None
    base_branch: typing.Optional[str] = None
    status_checks_passing: typing.Optional[bool] = None


class Rule(BaseModel):
    id: str
    type: RuleType
    description: str
    logic: str
    exceptions: typing.List[str]


class RuleEvaluation(BaseModel):
    rule_id: str
    status: RuleStatus
    reasoning: str


# #########################################################################
# Generated type aliases (0)
# #########################################################################
