# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {
    "types.CIFacts": types.CIFacts,
    "stream_types.CIFacts": stream_types.CIFacts,
    "types.CommitFacts": types.CommitFacts,
    "stream_types.CommitFacts": stream_types.CommitFacts,
    "types.Control": types.Control,
    "stream_types.Control": stream_types.Control,
    "types.CoverageFacts": types.CoverageFacts,
    "stream_types.CoverageFacts": stream_types.CoverageFacts,
    "types.EvidenceInput": types.EvidenceInput,
    "stream_types.EvidenceInput": stream_types.EvidenceInput,
    "types.IssueBoardFacts": types.IssueBoardFacts,
    "stream_types.IssueBoardFacts": stream_types.IssueBoardFacts,
    "types.PRFacts": types.PRFacts,
    "stream_types.PRFacts": stream_types.PRFacts,
    "types.PerformanceFacts": types.PerformanceFacts,
    "stream_types.PerformanceFacts": stream_types.PerformanceFacts,
    "types.Rule": types.Rule,
    "stream_types.Rule": stream_types.Rule,
    "types.RuleEvaluation": types.RuleEvaluation,
    "stream_types.RuleEvaluation": stream_types.RuleEvaluation,
    "types.SecurityFacts": types.SecurityFacts,
    "stream_types.SecurityFacts": stream_types.SecurityFacts,
    "types.TestResultFacts": types.TestResultFacts,
    "stream_types.TestResultFacts": stream_types.TestResultFacts,
    "types.EvidenceType": types.EvidenceType,
    "types.RuleStatus": types.RuleStatus,
    "types.RuleType": types.RuleType,
}
