# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {
    "types.Control": types.Control,
    "stream_types.Control": stream_types.Control,
    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,
    "types.Rule": types.Rule,
    "stream_types.Rule": stream_types.Rule,
    "types.RuleType": types.RuleType,
}
